### ISSUE TITLE
💻 [feature] 그룹 상세 정보

### ISSUE THREAD

**Issue by 5kiran** [Nomik94/LounGe#106]
# 💻 기능 개요

그룹 상세 정보
### ✅ TODO

- [ ] 그룹 상세 정보 컨트롤러
- [ ] 그룹 상세 정보 서비스
- [ ] 그룹 상세 정보 유닛테스트
