### ISSUE TITLE
💻 [feature] 그룹,유저 전체 이벤트 리스트 기능

### ISSUE THREAD

**Issue by 5kiran** [Nomik94/LounGe#130]
# 💻 기능 개요

그룹,유저 전체 이벤트 리스트 기능
### ✅ TODO

- [ ] 그룹,유저 전체 이벤트 리스트 컨트롤러
- [ ] 그룹,유저 전체 이벤트 리스트 서비스
- [ ] 그룹,유저 전체 이벤트 리스트 유닛테스트
