### ISSUE TITLE
💻 [feature] 유저 일정 상세보기

### ISSUE THREAD

**Issue by 5kiran** [Nomik94/LounGe#136]
# 💻 기능 개요

유저 일정 상세보기
### ✅ TODO

- [ ] 유저 일정 상세보기 컨트롤러
- [ ] 유저 일정 상세보기 서비스
- [ ] 유저 일정 상세보기 유닛테스트
