### ISSUE TITLE
💻 [feature] 그룹 가입 거절 기능

### ISSUE THREAD

**Issue by 5kiran** [Nomik94/LounGe#142]
# 💻 기능 개요

그룹 가입 거절 기능
### ✅ TODO

- [ ] 그룹 가입 거절 컨트롤러
- [ ] 그룹 가입 거절 서비스
- [ ] 그룹 가입 거절 유닛테스트
