### ISSUE TITLE
🔨 [refactor] 그룹 코드 리팩토링

### ISSUE THREAD

**Issue by 5kiran** [Nomik94/LounGe#148]
# 🔨 리팩토링이 필요한 부분 
그룹 클린 코드 리팩토링
# 리팩토링 작업 브런치

refactor/group
### ✅ TODO

- [ ] 쿼리빌더 사용 코드 Repository로 분리
- [ ] 함수, 변수 카멜케이스 및 함수명 동사를 앞으로 변경
- [ ] 안쓰는 코드, 주석, 콘솔로그 삭제
- [ ] DB 관련 제외 파일명 ex) create.user.dto.ts 와 같은 형식으로 변경
