### ISSUE TITLE
🔨 [refactor] 유저,로그인 코드 리팩토링

### ISSUE THREAD

**Issue by Nomik94** [Nomik94/LounGe#149]
# 🔨 리팩토링이 필요한 부분 
유저, 로그인 코드 리팩토링
# 리팩토링 작업 브런치

refactor/auth
### ✅ TODO

- [ ] 함수, 변수 카멜케이스 및 함수명 동사를 앞으로 변경
- [ ] 안쓰는 코드, 주석, 로그 삭제
- [ ] DB 관련 제외 파일명 ex) create.user.dto.ts 와 같은 형식으로 변경
- [ ] 컨트롤러, 서비스에 주석으로 간단한 설명 달기
