### ISSUE TITLE
💻 [feature] 그룹 리스트 확인 기능

### ISSUE THREAD

**Issue by 5kiran** [Nomik94/LounGe#15]
# 💻 기능 개요

그룹 리스트 확인 기능
### ✅ TODO

- [ ] 그룹 리스트 확인 컨트롤러
- [ ] 그룹 리스트 확인 서비스
- [ ] 그룹 리스트 컨트롤러 & 서비스 유닛 테스트
