### ISSUE TITLE
🔨 [refactor] 캘린더 코드 리팩토링

### ISSUE THREAD

**Issue by 5kiran** [Nomik94/LounGe#153]
# 🔨 리팩토링이 필요한 부분 
캘린더 클린 코드 리팩토링
# 리팩토링 작업 브런치

refactor/calendar
### ✅ TODO

- [x] 쿼리빌더 사용 코드 Repository로 분리
- [x] 함수, 변수 카멜케이스 및 함수명 동사를 앞으로 변경
- [x] 안쓰는 코드, 주석, 콘솔로그 삭제
- [x] DB 관련 제외 파일명 ex) create.user.dto.ts 와 같은 형식으로 변경
- [x] 컨트롤러, 서비스에 주석으로 간단한 설명 달기
- [x] 반복적으로 사용되는 코드 모듈화
- [x] 타입 정의
