### ISSUE TITLE
🔨 [refactor] 뉴스피드 코드 리팩토링

### ISSUE THREAD

**Issue by Joto-Han** [Nomik94/LounGe#155]
# 🔨 리팩토링이 필요한 부분 
뉴스피드 코드 리팩토링
# 리팩토링 작업 브런치

refactor/newsfeed
### ✅ TODO

- [ ] 안쓰는 코드 및 주석, 콘솔로그 삭제
- [ ] 함수 및 변수 카멜케이스 수정
- [ ] 함수명 동사 앞 현재시제 수정
- [ ] 서비스 및 레포지토리 분리
- [ ] 인터페이스 설정
- [ ] 서비스의 리턴 타입 지정
