### ISSUE TITLE
💻 [feature] 그룹 정보 수정 기능

### ISSUE THREAD

**Issue by 5kiran** [Nomik94/LounGe#17]
# 💻 기능 개요

그룹 정보 수정 기능
### ✅ TODO

- [ ] 그룹 정보 수정 컨트롤러
- [ ] 그룹 정보 수정 서비스
- [ ] 그룹 정보 컨트롤러 & 서비스 유닛 테스트
