### ISSUE TITLE
💻 [feature] 그룹 생성 기능

### ISSUE THREAD

**Issue by 5kiran** [Nomik94/LounGe#2]
# 💻 기능 개요

그룹 생성 기능
### ✅ TODO

- [ ] 그룹 생성 컨트롤러
- [ ] 그룹 생성 서비스
- [ ] 그룹 생성 컨트롤러 & 서비스 유닛 테스트
- [ ] 통합 테스트
