### ISSUE TITLE
💻 [feature] 그룹 탈퇴 기능

### ISSUE THREAD

**Issue by 5kiran** [Nomik94/LounGe#23]
# 💻 기능 개요

그룹 탈퇴 기능
### ✅ TODO

- [ ] 그룹 탈퇴 컨트롤러
- [ ] 그룹 탈퇴 서비스
- [ ] 그룹 탈퇴 컨트롤러 & 서비스 유닛 테스트
