### ISSUE TITLE
💻 [feature] 그룹 태그 검색 기능

### ISSUE THREAD

**Issue by 5kiran** [Nomik94/LounGe#24]
# 💻 기능 개요

그룹 태그 검색 기능
### ✅ TODO

- [ ] 그룹 태그 검색 컨트롤러
- [ ] 그룹 태그 검색 서비스
- [ ] 그룹 태그 검색 컨트롤러 & 서비스
