### ISSUE TITLE
💻 [feature] 그룹 기능 페이지 연동

### ISSUE THREAD

**Issue by 5kiran** [Nomik94/LounGe#85]
# 💻 기능 개요

그룹에 관련된 기능을 axios를 통해 백앤드와 통신시키기
### ✅ TODO

- [x] 그룹 생성
- [x] 그룹 수정
- [x] 그룹 삭제
- [x] 그룹 리스트 
- [x] 그룹 태그 검색
- [x] 그룹 가입 신청
- [x] 그룹 가입 수락
- [x] 그룹 탈퇴
- [x] 그룹장 그룹 리스트
- [x] 그룹 가입 신청자 리스트
- [x] 소속된 그룹 리스트 
- [x] 그룹 멤버 리스트 관리
- [x] 그룹 멤버 리스트 전체
- [x] 그룹 양도
- [x] 그룹 추방
- [x] 그룹 상세 정보
