### ISSUE TITLE
💻 [feature] 그룹장 그룹 리스트

### ISSUE THREAD

**Issue by 5kiran** [Nomik94/LounGe#86]
# 💻 기능 개요

그룹장 그룹 리스트
### ✅ TODO

- [ ] 그룹장 그룹 리스트 컨트롤러
- [ ] 그룹장 그룹 리스트 서비스
- [ ] 그룹장 그룹 리스트 유닛테스트
