### ISSUE TITLE
💻 [feature] 그룹 리스트(그룹원)

### ISSUE THREAD

**Issue by 5kiran** [Nomik94/LounGe#88]
# 💻 기능 개요

그룹 리스트(그룹원)
### ✅ TODO

- [ ] 그룹 리스트(그룹원) 컨트롤러
- [ ] 그룹 리스트(그룹원) 서비스
- [ ] 그룹 리스트(그룹원) 유닛테스트
