### ISSUE TITLE
💻 [feature] 그룹 추방

### ISSUE THREAD

**Issue by 5kiran** [Nomik94/LounGe#95]
# 💻 기능 개요

그룹 추방 기능
### ✅ TODO

- [ ] 그룹 추방 컨트롤러
- [ ] 그룹 추방 서비스
- [ ] 그룹 추방 유닛테스트
